---
# API and data storage info
rpc_username: rpc
rpc_password: rpc
bind: 127.0.0.1:8000
db_file: ./nyauser.db

# Where to send torrents
sinks:
  default:
    type: transmission
    url: http://localhost:9091/transmission/rpc
    username: transmission
    password: transmission

# Where to send torrents
sources:
  default:
    type: nyaa
    url: https://nyaa.si/?page=rss&c=0_0&f=0&q=

# Configure how searches behave
search:
  completion_check_minutes: 1
  search_minutes: 1
  min_seeders: 1
  max_days_old: 1000
  relocate: ./media/
  path_patch:
    "/data/completed": "~/Downloads"

# How to search and find shows
profiles:
  - name: subsplease
    search_prefix: "subsplease 1080p"
    parse_regex: '\[SubsPlease\] (?P<title>.*?) (?:S(?P<season>[0-9]{1,2}) )?- (?P<episode>(?:SP)?[0-9]{1,3}(?:\.\d)?)(?:v[0-9])? \(1080p\) \[(?P<checksum>[0-9a-zA-Z]{8})\]\.mkv'
  - name: subsplease720
    search_prefix: "subsplease 720p"
    parse_regex: '\[SubsPlease\] (?P<title>.*?) (?:S(?P<season>[0-9]{1,2}) )?- (?P<episode>(?:SP)?[0-9]{1,3}(?:\.\d)?)(?:v[0-9])? \(1080p\) \[(?P<checksum>[0-9a-zA-Z]{8})\]\.mkv'

# What shows to find
series:
  - name: Tonikaku Kawaii
    profile: subsplease
  - name: Spy x Family
    profile: subsplease
